version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: hamza
      POSTGRES_PASSWORD: hamza
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
      - spring
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres

  backend:
    container_name: backend
    image: hmaydaaabdo/backend:final2
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    container_name: frontend
    image:  hmaydaabdo/front:worked
    ports:
      - "9090:80"
    depends_on:
      - backend
    networks:
      - spring





networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: